export const icons = {
  burger: require("./icons/burger.png"),
  dessert: require("./icons/dessert.png"),
  down: require("./icons/down.png"),
  filter: require("./icons/filter.png"),
  home: require("./icons/home.png"),
  order: require("./icons/order.png"),
  pickup: require("./icons/pickup.png"),
  pin: require("./icons/pin.png"),
  right: require("./icons/right.png"),
  pizza: require("./icons/pickup.png"),
  search: require("./icons/search.png"),
  salad: require("./icons/salade.png"),
  profil: require("./icons/profil.png"),
  star: require("./icons/star.png"),
  steak: require("./icons/steak.png"),
  sushi: require("./icons/sushi.png"),
  vareniki: require("./icons/vareniki.png"),
};
